### ISSUE TITLE
Necessity for --with-cplex=false

### ISSUE THREAD

**Issue by akazachk** [coin-or/Osi#143] opened 2020-08-01 17:28 UTC
I have a report of a possibly unintended behavior when I was trying to follow the Quick Start example on a machine running Oracle Linux Server release 7.7. Specifically, I run these commands:

```
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew build Cbc@master
```

However, the build fails:

```
##################################################
### Building Osi master
##################################################

[COIN_INSTALL_DIR]/Osi/src/OsiCpx/OsiCpxSolverInterface.cpp:22:10: fatal error: cplex.h: No such file or directory
   22 | #include "cplex.h"
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [OsiCpxSolverInterface.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Build failed, see error output above
```

If I instead I call `./coinbrew build Cbc@master --with-cplex=false`, the build succeeds. Note that CPLEX is installed on the server, but perhaps in an unusual location.

It might be worth adding this information to the README + documentation and describe the `--with-cplex` option when calling `coinbrew -h`. I would also suggest telling the user they may need to call `chmod u+x coinbrew` in the Quick Start.

**Comment by tkralphs** [comment] 2020-08-02 16:03
The issue is now transferred.

**Comment by svigerske** [comment] 2020-08-03 10:05
Doing a warning only is a bit difficult without going deep into coin.m4, as it is difficult to undo some of the setting that the `AC_COIN_CHK_LIB` macro does at the end when it concluded that the library is present.

**Comment by akazachk** [comment] 2020-08-03 15:37
I think adding the descriptive error in 4ac0b26 is definitely an improvement.

I am not sure if this is already done, but possibly if the library check is concluded and CPLEX is found, maybe in addition to the standard include paths, `cplex.h` can be searched for in a modification of where the library was found. E.g., if the library is found in `/path/to/cplex/version/cplex/lib/x86-64_linux/static_pic`, then the base CPLEX directory is `CPLEX_DIR=/path/to/cplex/version` and the include path is likely to be `${CPLEX_DIR}/cplex/include/ilcplex`, I think (or `${CPLEX_DIR}/cplex/include` if the code has `#include <ilcplex/cplex.h>` not `#include <cplex.h>`).

Alternatively, it might help the user to state (in the error message) that they can either compile with `--without-cplex` (I just learned this was an option, as I have been doing `--with-cplex=false`) OR with `--with-cplex-incdir=...`.

**Comment by tkralphs** [comment] 2020-08-04 17:58
It seems reasonable to me just not to do the automatic link check if we don't also check for the header. We would just only check for the library if the user explicitly asks. How do we do this with other libraries? I would have thought we always check for the header, too, as this could be an issue with any library.

At any rate, this is a pretty unusual case where the CPLEX library path is in `LD_LIBRARY_PATH`, but the header is not installed in a system directory.

**Comment by svigerske** [comment] 2020-08-05 08:27
For libs like readline, zlib, gmp, we check for both the header and the library. For those, only the systems standard search paths are checked (no options to specify cflags and lflags).

**Closed as completed** 2020-12-10 19:26 UTC

**Comment by tkralphs** [comment] 2021-03-02 03:07
There is now further work on this in https://github.com/coin-or-tools/BuildTools/#143 and https://github.com/coin-or-tools/BuildTools/#148.
